name: fit2form
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.9.0=py37_0
  - anaconda-client=1.7.2=py37_0
  - anaconda-navigator=1.9.12=py37_0
  - asciitree=0.3.3=py_2
  - attrs=19.3.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.tempfile=1.0=py_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.9.1=py37_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.10.14=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.4.1=py_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.3=py_0
  - conda=4.9.2=py37h06a4308_0
  - conda-build=3.18.11=py37_0
  - conda-env=2.6.0=1
  - conda-package-handling=1.6.1=py37h7b6447c_0
  - conda-verify=3.4.2=py_1
  - cryptography=2.9.2=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask-core=2.19.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he6710b0_2
  - fasteners=0.14.1=py_3
  - filelock=3.0.12=py_0
  - flake8=3.8.3=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - future=0.18.2=py37_1
  - glib=2.63.1=h5a9c865_0
  - glob2=0.7=py_0
  - google-auth=1.20.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - imageio=2.8.0=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.1=217
  - ipython_genutils=0.2.0=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py37_0
  - jupyter_core=4.6.3=py37_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libarchive=3.4.2=h62408e4_0
  - libedit=3.1.20191231=h7b6447c_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblief=0.10.1=he6710b0_0
  - libllvm9=9.0.1=h4a3c616_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.4=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - llvmlite=0.33.0=py37hd408876_0
  - lz4-c=1.9.2=he6710b0_0
  - markdown=3.2.2=py37_0
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37hef1b27d_0
  - mccabe=0.6.1=py37_1
  - mkl=2020.1=217
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.1.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - monotonic=1.5=py_0
  - msgpack-python=1.0.0=py37h99015e2_1
  - navigator-updater=0.2.1=py37_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numba=0.50.1=py37h0573a6f_0
  - numcodecs=0.6.4=py37he1b5a44_0
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h7b6447c_0
  - patchelf=0.11=he6710b0_0
  - pcre=8.44=he6710b0_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pkginfo=1.5.0.1=py37_0
  - psutil=5.7.0=py37h7b6447c_0
  - py-lief=0.10.1=py37h403a769_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybind11=2.5.0=py37hfd86e86_0
  - pycodestyle=2.6.0=py_0
  - pycosat=0.6.3=py37h7b6447c_0
  - pycparser=2.20=py_0
  - pyflakes=2.2.0=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - python-libarchive-c=2.9=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - qt=5.9.7=h5867ecd_1
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - ripgrep=11.0.2=he32d670_0
  - rsa=4.6=py_0
  - ruamel_yaml=0.15.87=py37h7b6447c_1
  - scikit-image=0.16.2=py37h0573a6f_0
  - scipy=1.5.0=py37h0b6359f_0
  - setuptools=47.3.1=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - soupsieve=2.0.1=py_0
  - sqlite=3.32.3=h62c20be_0
  - tbb=2020.0=hfd86e86_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.7.0=py37_cu101
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.47.0=py_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.9=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py37_0
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zarr=2.4.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - aiohttp==3.6.2
    - appdirs==1.4.4
    - async-timeout==3.0.1
    - blessings==1.7
    - colorzero==1.1
    - freetype-py==2.1.0.post1
    - gitdb==4.0.5
    - gitpython==3.1.3
    - google==2.0.3
    - gpiozero==1.5.1
    - gpustat==0.6.0
    - greenlet==0.4.16
    - grpcio==1.28.1
    - gym==0.17.1
    - jedi==0.17.1
    - lxml==4.5.1
    - mako==1.1.3
    - more-itertools==8.4.0
    - multidict==4.7.5
    - neovim==0.3.1
    - networkx==2.2
    - numpy-quaternion==2020.4.24.9.29.7
    - nvidia-ml-py3==7.352.0
    - packaging==20.4
    - parso==0.7.0
    - pip==20.2.4
    - pluggy==0.13.1
    - protobuf==3.11.3
    - py==1.9.0
    - py-spy==0.3.3
    - pybullet==3.0.6
    - pycollada==0.6
    - pycuda==2019.1.2
    - pygifsicle==1.0.1
    - pyglet==1.5.0
    - pynvim==0.4.1
    - pyopengl==3.1.0
    - pyquaternion==0.9.9
    - pyrender==0.1.43
    - pysimplegui==4.22.0
    - pytest==5.4.3
    - pytools==2020.2
    - ray==0.8.5
    - redis==3.4.1
    - shapely==1.7.0
    - smmap==3.0.4
    - tensorboardx==2.0
    - transforms3d==0.3.1
    - urdfpy==0.0.22
    - wcwidth==0.2.5
    - yarl==1.4.2
prefix: /home/hqh2101/anaconda3
